# Install docker and it's component. 
---
  - name: Copy dockerhost.repo
    copy:
      src: dockerhost.repo
      dest: /etc/yum.repos.d/

  - name: Uninstall older version of docker
    yum: 
      name: "{{ item }}" 
      state: absent
    with_items:
      - docker
      - docker-client
      - docker-common

  - name: Install Package | Docker
    yum:
      name: "{{ item }}"
      state: latest
    with_items:
      - docker-ce
      - docker-compose

  - name: Start Service | Docker
    service:
      name: docker
      state: started
      enabled: yes
