# Playbook deployes Qjenkins on jenkins hosts inside pod
--- 
- hosts: Jenkins
  gather_facts: True
  become: True
  vars_files:
    - vars/main.yml
  roles:
    - common
    - nginx
    - docker
  tasks:
  - name: Copy jenkins.repo
    copy:
      src: jenkins.repo
      dest: /etc/yum.repos.d/
  - name: Install jenkins
    yum:
      name: jenkins
      state: latest
  - name: Copy config file
    template:
      src: config.xml.j2
      dest: /opt/jenkins/jenkins_home/config.xml
      mode: 0644
  - name: Copy Jenkins URL xml
    template:
      src: jenkins.model.JenkinsLocationConfiguration.xml.j2
      dest: /opt/jenkins/jenkins_home/jenkins.model.JenkinsLocationConfiguration.xml
      mode: 0644
  - name: Enable jenkins Service
    service:
      name: jenkins
      state: started
      enabled: yes
    notify: restart nginx
